<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5656" started-at="2020-06-11T12:35:40Z" finished-at="2020-06-11T12:35:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5656" started-at="2020-06-11T12:35:40Z" finished-at="2020-06-11T12:35:45Z">
      <class name="testCases.order.TC_Recent_Phone_Number">
        <test-method status="PASS" signature="setup()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab]" name="setup" is-config="true" duration-ms="73" started-at="2020-06-11T12:35:40Z" finished-at="2020-06-11T12:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-06-11T12:35:40Z" finished-at="2020-06-11T12:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testRecentPhoneNumber()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab]" name="testRecentPhoneNumber" duration-ms="5541" started-at="2020-06-11T12:35:40Z" finished-at="2020-06-11T12:35:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testCases.order.TC_Recent_Phone_Number.testRecentPhoneNumber(TC_Recent_Phone_Number.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRecentPhoneNumber -->
        <test-method status="SKIP" signature="checkData()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab]" name="checkData" duration-ms="1" started-at="2020-06-11T12:35:45Z" depends-on-methods="testCases.order.TC_Recent_Phone_Number.testRecentPhoneNumber" finished-at="2020-06-11T12:35:45Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_Recent_Phone_Number.checkData()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_Recent_Phone_Number.checkData()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkData -->
        <test-method status="SKIP" signature="checkDB()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab]" name="checkDB" duration-ms="0" started-at="2020-06-11T12:35:45Z" depends-on-methods="testCases.order.TC_Recent_Phone_Number.checkData" finished-at="2020-06-11T12:35:45Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_Recent_Phone_Number.checkDB()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_Recent_Phone_Number.checkDB()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDB -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testCases.order.TC_Recent_Phone_Number@3b2cf7ab]" name="afterClass" is-config="true" duration-ms="9" started-at="2020-06-11T12:35:45Z" finished-at="2020-06-11T12:35:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- testCases.order.TC_Recent_Phone_Number -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
